// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static final FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDkoXNMJ5MVF-5WuMOs7qgDV9zLvxVh1f0',
  appId: '1:732214791150:web:acc025c082984d7ad1dcff',
  messagingSenderId: '732214791150',
  projectId: 'auto-service-app-f4166',
  authDomain: 'auto-service-app-f4166.firebaseapp.com',
  storageBucket: 'auto-service-app-f4166.firebasestorage.app',
  measurementId: 'G-3SQX72ZE0J',
);

static final FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyBZZe-hE0j-GpWCp762U6XqossHbvjR7gM',
  appId: '1:732214791150:android:6c7b11fcf31e6724d1dcff',
  messagingSenderId: '732214791150',
  projectId: 'auto-service-app-f4166',
  storageBucket: 'auto-service-app-f4166.firebasestorage.app',
);

static final FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyDgIOm4_ZZyeBZOIZpFXAOY3mCYajJx6AY',
  appId: '1:732214791150:ios:6ff347255a886566d1dcff',
  messagingSenderId: '732214791150',
  projectId: 'auto-service-app-f4166',
  storageBucket: 'auto-service-app-f4166.firebasestorage.app',
  iosBundleId: 'com.example.autoServiceApp',
);

}
